# Site settings
title: Technopaki
description:
#baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog

# User settings
username: Technopaki
user_description: Make cool things!
user_title:
#email: anon@anon.com
facebook_username: Technopaki
youtube_username: UCAcJEEe_RHFADrM958X0SYw
twitter_username: Technopaki
github_username:  Tr4in
disqus_username: www-technopaki-at

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Anylytics
google-analytics: "UA-88541104-1"


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Kategorien
    url: /tags

# Imprint etc. ...
footerinfo:
  - imprint: Impressum
    url: /impressum
  - privacy: Datenschutz
    url: /datenschutz

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', .firebaserc, firebase.json]
